version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Chicharito17
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"